### ISSUE TITLE
rankingTrixiumPlayerLeaderboard Problem issue

### ISSUE THREAD

**Issue by OxydeDev1789** [TonyKun7/npm-paladiumapi#1]
Bonjour la fonction rankingTrixiumPlayerLeaderboard ne marche plus depuis le changement de domaine de l'api Paladium la data de TotalCount me renvoie un undefined avez vous identifié le problème ?

**Comment by TonyKun7** [comment]
`{
  status: 404,
  data: {
    type: 'INVALID_REQUEST_ERROR',
    message: "Endpoint 'trixium/player' not found for service 'ranking' on version '1' with method 'GET'."
  }
}`

Bug de l'api pas du module

**Comment by OxydeDev1789** [comment]
Okay merci de votre réponse désolé du dérangement alors ^^ je vous souhaite une bonne journée
